use_frameworks!

target 'example_Example' do
  pod 'example', :path => '../'

  target 'example_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
